version: 0.2

phases:
  install:
    commands:
      - yum install sbt
  pre_build:
    commands:
      - REPOSITORY_NAME=game
  build:
    commands:
      - printf '{"repository":"%s"}' $REPOSITORY_NAME > build.json
      - sbt test
      - sbt assembly
artifacts:
  files:
    - target/scala-3.2.2/*.jar
    - build.json