version: 0.2

phases:
  install:
    commands:
      - sudo rm -f /etc/yum.repos.d/bintray-rpm.repo
      - curl -L https://www.scala-sbt.org/sbt-rpm.repo > sbt-rpm.repo
      - sudo mv sbt-rpm.repo /etc/yum.repos.d/
      - sudo yum install -y sbt
  pre_build:
    commands:
      - REPOSITORY_NAME=game
  build:
    commands:
      - printf '{"repository":"%s"}' $REPOSITORY_NAME > build.json
      - cd game
      - sbt test
      - sbt assembly
artifacts:
  files:
    - game/target/scala-3.2.2/*.jar
    - game/build.json